### ISSUE TITLE
Should OK and Cancel buttons have predefined colors?

### ISSUE THREAD

**Issue by aligoren** [f/confirmation#1]
Should OK and Cancel buttons have predefined colors like sweet alert 2?

For example

```js
await confirmation(
  'Warning',
  'You will delete your items, are you sure?',
  {
     ok: {
         text: 'I am sure',
         type: 'information' // light blue
     },
     cancel: {
         text: 'No!',
         type: 'warning' // Orange tone
     }
  }
)
```

**Comment by f** [comment]
This would be too complex just for a `window.confirm` replacement.

**Comment by aligoren** [comment]
Okay, It might be nice for `window.alert` replacement. Thanks.

I'll close this issue If you will not say anything.
