### ISSUE TITLE
Default key mappings

### ISSUE THREAD

**Issue by gokaygurcan** [f/confirmation#2]
Hoi,

Usually, Y and N keys are being used to confirm or to cancel a confirmation. Using O and C is not just weird but also out of industry standards. 

That'd be nice to have some kind of default mapping for Y and N, and a support to customise it if necessary. 

Thanks for this "experiment".

Best,
G.

**Comment by f** [comment]
Sure, this can be improved.

**Comment by f** [comment]
Done.

**Comment by gokaygurcan** [comment]
Thank you <3
